### ISSUE TITLE
Unable to run a prod build

### ISSUE THREAD

**Issue by alexhorner** [ExpDev07/legacy-rp-admin-v3#260]
**Describe the bug**
Following the setup instructions, I am unable to run the prod script

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'prod' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'preprod', 'prod', 'postprod' ]
5 info lifecycle @~preprod: @
6 info lifecycle @~prod: @
7 verbose lifecycle @~prod: unsafe-perm in lifecycle true
8 verbose lifecycle @~prod: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/fivem/LegacyRPAdmin/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle @~prod: CWD: /home/fivem/LegacyRPAdmin
10 silly lifecycle @~prod: Args: [ '-c', 'npm run production' ]
11 silly lifecycle @~prod: Returned: code: 1  signal: null
12 info lifecycle @~prod: Failed to exec prod script
13 verbose stack Error: @ prod: `npm run production`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @
15 verbose cwd /home/fivem/LegacyRPAdmin
16 verbose Linux 5.4.0-84-generic
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "run" "prod"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error @ prod: `npm run production`
22 error Exit status 1
23 error Failed at the @ prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**To Reproduce**
1. Clean copy of the latest repo
2. Use a non-root user without sudo privileges
3. Go through the setup guide. The only .env modifications I made where the mysql credentials

**Expected behavior**
Prod build works as indended

**Screenshots**
![image](https://user-images.githubusercontent.com/33007665/133153273-b3c0094f-7ffd-4c45-bc20-fba0c2efb09b.png)

**Comment by alexhorner** [comment]
More detailed screenshot
![image](https://user-images.githubusercontent.com/33007665/133154701-ebf7a7a3-50e6-4ae5-b12b-0be4bce6dba0.png)

**Comment by milan60** [comment]
Hmm, that's weird. I'm not having that issue on my machine. The error message seems to come from one of the node_modules. @ExpDev07 do you know more?

**Comment by ExpDev07** [comment]
Indeed weird. This is after running npm install?

**Comment by ExpDev07** [comment]
Seems like your node version is outdated / not supported for tailwind. See https://github.com/tailwindlabs/tailwindcss/issues/921. Update your node and npm :).

**Comment by alexhorner** [comment]
Looks like this worked, thank you!
